project_id = "ezymoplfpsjpklskgodn"

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.verify-product-access]
verify_jwt = true
